program: fbt/experiments/compare_stats.py
command:
  - python3
  - fbt/experiments/compare_stats.py
  - --inference_method=fn
  - --experiment_setup=prequential
  - --config_data=intermediate_graph_abm_02
  - --config_model=model_ABM01
name: default
method: grid
project: dpfn-dpfn_experiments
metric:
  goal: minimize
  name: pir_mean
parameters:
  model.num_rounds:
    values: [5]
  model.num_days_window:
    values: [14] 
  data.fraction_test:
    values: [0.06]
  model.quantization:
    values: [512]
  data.fraction_stale:
    values: [-1]
  data.t_start_quarantine:
    values: [3]
  model.policy:
    values: ["combi,age,norm_score"] 
  model.test_stochastic:
    values: [0] 
  model.hybrid_split:
    values: [0]
  model.oracle:
    values: [0]
  model.t_days:
    values: [100]
  model.feature_weight_0:
    values: [1.0] 
  model.feature_weight_1:
    values: [1e-13, 0.3, 10]
  model.feature_weight_2:
    values: [0] 
  model.feature_pow_1:
    values: [1.0] 
  model.feature_pow_2:
    values: [1.0] 
  model.noisy_test:
    values: [-1] 
  model_seed:
    values: [201] 
  sim_seed:
    values: [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199]